name: continuous-integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install bats
        run: npm install -g bats

      - name: Install expect
        run: sudo apt-get install expect doas

      - name: Run tests
        run: make test
