name: continuous-integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, fedora-latest, archlinux ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install bats
        run: npm install -g bats

      - name: Run tests
        run: make test
