name: continuous-integration

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install bats
        run: npm install -g bats

      - name: Run tests
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux
        run: bats --print-output-on-failure --formatter tap tests
